[features]
seeds = false
skip-lint = false
[programs.localnet]
twitter = "D1XHmse2CeLU1hcoNhFeVzVsqcspLUqavv2CZPP6bWBF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/cloud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
